name: Flutter APK Builder

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Recreate Android Project Files
      run: |
        mkdir -p backup_lib
        cp -r lib/* backup_lib/ || true
        cp pubspec.yaml backup_pubspec.yaml || true
        
        flutter create --org com.tippelemzo --project-name ai_tippelemzo_pro .
        
        rm -rf lib
        mv backup_lib lib
        mv backup_pubspec.yaml pubspec.yaml

    - name: Inject Android Internet Permission
      run: |
        # Beírjuk az internet engedélyt a generált AndroidManifest.xml fájlba
        MANIFEST_PATH="android/app/src/main/AndroidManifest.xml"
        if [ -f "$MANIFEST_PATH" ]; then
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"\/>' $MANIFEST_PATH
          echo "Internet permission successfully injected!"
        fi

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
